# Generated by Django 3.2 on 2021-05-12 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThatsAppUser',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=500, verbose_name='nickname')),
                ('mqtt_topic', models.CharField(blank=True, max_length=1000, verbose_name='topic')),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ThatsAppUser',
                'verbose_name_plural': 'ThatsAppUsers',
            },
        ),
    ]
