# Generated by Django 3.2 on 2021-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThatsAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=500, verbose_name='nickname')),
                ('mqtt_topic', models.CharField(max_length=1000, verbose_name='topic')),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ThatsAppUser',
                'verbose_name_plural': 'ThatsAppUsers',
            },
        ),
    ]
