# Generated by Django 3.2 on 2021-05-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thatsappuser',
            name='avatar',
            field=models.URLField(default='', verbose_name='avatar url'),
            preserve_default=False,
        ),
    ]
