# Generated by Django 3.2 on 2021-05-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thatsappuser',
            name='nickname',
            field=models.CharField(max_length=500, unique=True, verbose_name='nickname'),
        ),
    ]
