# Generated by Django 3.2 on 2021-05-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_thatsappuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='thatsappuser',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='avatar'),
        ),
    ]
