# Generated by Django 3.2 on 2021-05-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_thatsappuser_mqtt_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thatsappuser',
            name='mqtt_topic',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True, verbose_name='topic'),
        ),
    ]
